name: "ClapTrap"
version: "2.1.0"
slug: "claptrap"
description: "Application de détection d'applaudissements en temps réel utilisant YAMNet, compatible avec les flux audio locaux et RTSP"
url: "https://github.com/lfpoulain/ClapTrap-HA-Addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
host_network: true
#ports:
#  "16045/tcp": 16045
#  "6980/tcp": 6980
init: false
webui: "http://[HOST]:[PORT:16045]"
maintainer: "lfpoulain"
